const labels={
    CANCEL: "Cancel",
    DELETE: "Delete",
    BOARDS:"Boards",
    BOARD:"Board",
    PIN:"Pin",
    CREATE:"Create",
    DONE:"Done",
    SAVE:"Save",
    FOLLOWERS:"Followers",
    UNFOLLOW:"Unfollow",
    FOLLOW:"Follow",
    FOLLOWING:"Following",
    THAS_YOU:"That's you",
    DELETE_PIN:"Delete Pin",
    SAVE_PIN:"Save Pin",
    DOWNLOAD_PIN:"Download Pin",
    PIN_REMOVED_EDIT_TOAST_MESSAGE:(board:string)=>`Pin is removed from your ${board}`,
    PIN_SAVED_BOARD_TOAST_MESSAGE:"Pin is saved in your board",
    PIN_SAVED_TITLE:(board:string)=>`This Pin is already saved in ${board}`,
    OTHER_BOARDS:"Other Boards",
    NO_BOARD_MESSAGE:"Their is not any board for this user.",
    CREATE_BOARD:"Create Board",
    ALL_PINS:"All Pins",
    SAVED:"Saved",
    NAME:"Name",
    DUPLICATE_BOARD_NAME_WARNING:"This board name is already taken.",
    BOARD_NAME_PLACEHOLDER:'Like "Watching Anime" or "Traveling"',
    QUICK_SAVE_TITLE:"Quick save and organize later",
    PROFILE:"Profile",
    SAVE_TO_BOARD:"Save to board",
    BOARD_CREATED_TITLE:"Board Created",
    SAVE_PIN_TO:(boardName:string)=>`You saved this pin to ${boardName}`,
    DESCRIPTION:"Description",
    DESCRIPTION_BOARD_PLACEHOLDER:"What's your board about",
    PIN_CREATE_BY:"pin created by",
    DELETE_BOARD:"Delete board",
    EDIT_PIN_TITLE:"Edit Pin",
    PIN_DETAIL_UPDATE_TOAST_MESSAGE:"Pin details is updated",
    PIN_DETAIL_UPDATE_ERROR_TOAST_MESSAGE:"Some problem while updating pin details",
    PIN_DETELTE_TOAST_MESSAGE:"Pin deleted successfully",
    PIN_DETELTE_ERROR_TOAST_MESSAGE:"Some problem while deleting pin",
    TITLE:"TITLE",
    TITLE_PLACEHOLDER:"Add a title",
    DESCRIPTION_PIN_PLACEHOLDER:"Add a detailed description",
    CHOOSE_BOARD_TITLE:"Choose a board",
    FOLLOWING_TOAST_MESSAGE:(name:string)=>`You start following ${name}`,
    UNFOLLOWING_TOAST_MESSAGE:(name:string)=>`You Unfollow ${name}`,
    NEED_TO_LOGIN:"isNeedToLogin",
    PINIT:"PinIt",
    HOME:"Home",
    ABOUT:"About",
    LOG_IN:"Log in",
    SIGN_UP:"Sign up",
    HOME_PAGE_TITLE1:'Get Your idea for Next',
    HOME_PAGE_TITLE2:'Fun | project | Creative | Art',
    HOME_PAGE_FOOTER:"Enjoy your pins collection's",
    ACCESS_TOKEN:"accessToken",
    PIN_SAVED_PROFILE_TOAST_MESSAGE:"Pin is saved in your profile",
    PIN_REMOVE_PROFILE_TOAST_MESSAGE:"Pin is removed from your profile",
    DONWLOAD:'Download',
    WELCOME_USER_TOAST_MESSAGE:(name:string)=>`Welcome back, ${name}`,
    INVALID_USER_TOAST_MESSAGE:"Invalid user credientials",
    USER_NOT_EXIST_TOAST_MESSAGE:"User does not exists",
    LOGIN_TITLE:"Welcome to PinIt",
    EMAIL:"Email",
    PASSWORD:"Password",
    SIGN_UP_GOOGLE:'Sign up with Google',
    NOT_SIGN_UP:"Not on PinIt yet ? Sign up",
    SIGN_UP_MODAL_TITLE:"Lets have fun and find video or image as per you mood",
    NOT_FOUND_TITLE:"The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.",
    NOT_FOUND_GO_HOME_PAGE:"Go to Home Page",
    HOVER_ON_ALL_PINS:'allPins',
    HOVER_ON_CREATED:"created",
    HOVER_ON_HOME_PIN:"homePin",
     OPEN:"OPEN",
     SEARCH_PLACEHOLDER:"Search",
     WHATSAPP:"Whatsapp",
     WHATSAPP_SEND_MESSAGE:"I found some funny pins for you in PinIt!",
     CREATED:"Created",
     SHARE:"Share",
     NO_PIN_CREATED:" Nothing to show...yet! Pins you create will live here",
     CREATE_PIN:"Create Pin",
     NO_PIN_SAVE_MESSAGE:(name:string)=>`${name} hasn't saved any pins yet`,
     SAVE_TO_PROFILE:"Save to profile",
     SIGN_UP_SUCCESS_TOAST_MESSAGE:(name:string)=>`Congratulations! ${name} Your account has been created.`,
     ALL_FIELDS_REQUIRED:"Please fill all the required fields",
     USER_EXISTED:"User with this email already exists",
     AVATAR:'Avatar',
     FULL_NAME:"Full Name",
     USER_NAME:"Username",
     ALREADY_MEMBER:"Already have a member ? log in",
     VIEW_OPTIONS:'View Options',
     DEFAULT:"Default",
     STANDARD:"Standard",
     STANDARD_VALUE:"standard",
     COMPACT:"Compact",
     COMPACT_VALUE:"compact",
     NO_PIN_SAVED_YET:"There aren’t any Pins saved yet",
     PIN_SAVED_IN_BOARD_TOAST_MESSAGE:(boardName:string)=>`Pin is saved in ${boardName} board`,
     REMOVE_PIN:"removed pin",
     MORE_TO_EXPLORE:"More to explore",
     FETCHING_PINS_ERROR:'Something went wrong, while fetching pins',
     NO_PINS_FOUND:"No pins found",
     UNAUTHORIZED_USER:"Unauthorized user",
     FILE_IS_REQUIRED:"File is required",
     NOT_PUBLISHED_ERROR: "Sorry!, due to some problem pin not able to published",
     PUBLISH:"Publish",
     CHOOSE_FILE_DRAG_DROP:"Choose a file or drag and drop it here",
     FILE_RECOMMEND_20_MB:"We recommend using high quality files less than 20MB",
     LESS_THAN_200_MB:"or .mp4 files less than 200MB",
     LINK:"Link",
     LINK_PLACEHOLDER:"Add a link",
     TAG:"Tags",
     TAG_PLACEHOLDER:"Add a tag",
     SOME_PIN_TO_SAVE_IN_BOARD:"Save some pins to your new board",
     CREATE_PIN_PUBLISHED_TOAST_MESSAGE:"Your pin has been published",
     LOGOUT:"Logout",
     MORE_OPTIONS:"More Options",
     CURRENTLY_IN:"Currently in",
     SIGN_ERROR:"Oops! Something went wrong. Please try signing up again later."

}
export {labels}